// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Category defines model for Category.
type Category struct {
	CreatedAt   time.Time `json:"createdAt"`
	Description *string   `json:"description"`
	Id          int       `json:"id"`
	Name        string    `json:"name"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

// CategoryCreateRequest defines model for CategoryCreateRequest.
type CategoryCreateRequest struct {
	Description *string `json:"description"`
	Name        string  `json:"name"`
}

// CategoryListResponse defines model for CategoryListResponse.
type CategoryListResponse struct {
	Data []Category     `json:"data"`
	Meta PaginationMeta `json:"meta"`
}

// CategoryUpdateRequest defines model for CategoryUpdateRequest.
type CategoryUpdateRequest = CategoryCreateRequest

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`

	// TraceId Correlation or trace identifier.
	TraceId *string `json:"traceId"`
}

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	Page       int `json:"page"`
	PageSize   int `json:"pageSize"`
	TotalItems int `json:"totalItems"`
	TotalPages int `json:"totalPages"`
}

// Product defines model for Product.
type Product struct {
	CategoryId      int       `json:"categoryId"`
	CreatedAt       time.Time `json:"createdAt"`
	Discontinued    bool      `json:"discontinued"`
	Id              int       `json:"id"`
	Name            string    `json:"name"`
	QuantityPerUnit *string   `json:"quantityPerUnit"`
	ReorderLevel    *int      `json:"reorderLevel,omitempty"`
	SupplierId      int       `json:"supplierId"`
	UnitPrice       float64   `json:"unitPrice"`
	UnitsInStock    int       `json:"unitsInStock"`
	UnitsOnOrder    *int      `json:"unitsOnOrder,omitempty"`
	UpdatedAt       time.Time `json:"updatedAt"`
}

// ProductCreateRequest defines model for ProductCreateRequest.
type ProductCreateRequest struct {
	CategoryId      int     `json:"categoryId"`
	Discontinued    *bool   `json:"discontinued,omitempty"`
	Name            string  `json:"name"`
	QuantityPerUnit *string `json:"quantityPerUnit"`
	ReorderLevel    *int    `json:"reorderLevel,omitempty"`
	SupplierId      int     `json:"supplierId"`
	UnitPrice       float64 `json:"unitPrice"`
	UnitsInStock    *int    `json:"unitsInStock,omitempty"`
	UnitsOnOrder    *int    `json:"unitsOnOrder,omitempty"`
}

// ProductListResponse defines model for ProductListResponse.
type ProductListResponse struct {
	Data []Product      `json:"data"`
	Meta PaginationMeta `json:"meta"`
}

// ProductUpdateRequest defines model for ProductUpdateRequest.
type ProductUpdateRequest = ProductCreateRequest

// Supplier defines model for Supplier.
type Supplier struct {
	Address      *string   `json:"address"`
	City         *string   `json:"city"`
	CompanyName  string    `json:"companyName"`
	ContactName  *string   `json:"contactName"`
	ContactTitle *string   `json:"contactTitle"`
	Country      *string   `json:"country"`
	CreatedAt    time.Time `json:"createdAt"`
	Id           int       `json:"id"`
	Phone        *string   `json:"phone"`
	PostalCode   *string   `json:"postalCode"`
	Region       *string   `json:"region"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

// SupplierCreateRequest defines model for SupplierCreateRequest.
type SupplierCreateRequest struct {
	Address      *string `json:"address"`
	City         *string `json:"city"`
	CompanyName  string  `json:"companyName"`
	ContactName  *string `json:"contactName"`
	ContactTitle *string `json:"contactTitle"`
	Country      *string `json:"country"`
	Phone        *string `json:"phone"`
	PostalCode   *string `json:"postalCode"`
	Region       *string `json:"region"`
}

// SupplierListResponse defines model for SupplierListResponse.
type SupplierListResponse struct {
	Data []Supplier     `json:"data"`
	Meta PaginationMeta `json:"meta"`
}

// SupplierUpdateRequest defines model for SupplierUpdateRequest.
type SupplierUpdateRequest = SupplierCreateRequest

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	Password string `json:"password"`

	// Scope Space-delimited scopes requested.
	Scope    string `json:"scope"`
	Username string `json:"username"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken string `json:"accessToken"`

	// ExpiresIn Token lifetime in seconds.
	ExpiresIn    int     `json:"expiresIn"`
	RefreshToken *string `json:"refreshToken"`
	TokenType    string  `json:"tokenType"`
}

// ValidationErrorResponse defines model for ValidationErrorResponse.
type ValidationErrorResponse struct {
	Code   string `json:"code"`
	Errors *[]struct {
		Field   string `json:"field"`
		Message string `json:"message"`
	} `json:"errors,omitempty"`
	Message string `json:"message"`

	// TraceId Correlation or trace identifier.
	TraceId *string `json:"traceId"`
}

// CategoryIdParam defines model for CategoryIdParam.
type CategoryIdParam = int

// PageParam defines model for PageParam.
type PageParam = int

// PageSizeParam defines model for PageSizeParam.
type PageSizeParam = int

// ProductIdParam defines model for ProductIdParam.
type ProductIdParam = int

// SortParam defines model for SortParam.
type SortParam = string

// SupplierIdParam defines model for SupplierIdParam.
type SupplierIdParam = int

// ListCategoriesParams defines parameters for ListCategories.
type ListCategoriesParams struct {
	// Page Page number to return.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Maximum number of records per page.
	PageSize *PageSizeParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`

	// Sort Sort expression, prefix field with '-' for descending order.
	Sort *SortParam `form:"sort,omitempty" json:"sort,omitempty"`

	// Name Filter categories by name substring.
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// ListProductsParams defines parameters for ListProducts.
type ListProductsParams struct {
	// Page Page number to return.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Maximum number of records per page.
	PageSize *PageSizeParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`

	// Sort Sort expression, prefix field with '-' for descending order.
	Sort *SortParam `form:"sort,omitempty" json:"sort,omitempty"`

	// Name Filter products by name substring.
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// CategoryId Filter products by category identifier.
	CategoryId *int `form:"categoryId,omitempty" json:"categoryId,omitempty"`

	// SupplierId Filter products by supplier identifier.
	SupplierId *int `form:"supplierId,omitempty" json:"supplierId,omitempty"`

	// Discontinued Filter products by discontinued flag.
	Discontinued *bool `form:"discontinued,omitempty" json:"discontinued,omitempty"`
}

// ListSuppliersParams defines parameters for ListSuppliers.
type ListSuppliersParams struct {
	// Page Page number to return.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Maximum number of records per page.
	PageSize *PageSizeParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`

	// Sort Sort expression, prefix field with '-' for descending order.
	Sort *SortParam `form:"sort,omitempty" json:"sort,omitempty"`

	// CompanyName Filter suppliers by company name substring.
	CompanyName *string `form:"companyName,omitempty" json:"companyName,omitempty"`

	// Country Filter suppliers by country.
	Country *string `form:"country,omitempty" json:"country,omitempty"`
}

// IssueTokenJSONRequestBody defines body for IssueToken for application/json ContentType.
type IssueTokenJSONRequestBody = TokenRequest

// CreateCategoryJSONRequestBody defines body for CreateCategory for application/json ContentType.
type CreateCategoryJSONRequestBody = CategoryCreateRequest

// UpdateCategoryJSONRequestBody defines body for UpdateCategory for application/json ContentType.
type UpdateCategoryJSONRequestBody = CategoryUpdateRequest

// CreateProductJSONRequestBody defines body for CreateProduct for application/json ContentType.
type CreateProductJSONRequestBody = ProductCreateRequest

// UpdateProductJSONRequestBody defines body for UpdateProduct for application/json ContentType.
type UpdateProductJSONRequestBody = ProductUpdateRequest

// CreateSupplierJSONRequestBody defines body for CreateSupplier for application/json ContentType.
type CreateSupplierJSONRequestBody = SupplierCreateRequest

// UpdateSupplierJSONRequestBody defines body for UpdateSupplier for application/json ContentType.
type UpdateSupplierJSONRequestBody = SupplierUpdateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Issue JWT token
	// (POST /auth/token)
	IssueToken(c *gin.Context)
	// List categories
	// (GET /categories)
	ListCategories(c *gin.Context, params ListCategoriesParams)
	// Create category
	// (POST /categories)
	CreateCategory(c *gin.Context)
	// Delete category
	// (DELETE /categories/{categoryId})
	DeleteCategory(c *gin.Context, categoryId CategoryIdParam)
	// Get category by ID
	// (GET /categories/{categoryId})
	GetCategory(c *gin.Context, categoryId CategoryIdParam)
	// Update category
	// (PUT /categories/{categoryId})
	UpdateCategory(c *gin.Context, categoryId CategoryIdParam)
	// List products
	// (GET /products)
	ListProducts(c *gin.Context, params ListProductsParams)
	// Create product
	// (POST /products)
	CreateProduct(c *gin.Context)
	// Delete product
	// (DELETE /products/{productId})
	DeleteProduct(c *gin.Context, productId ProductIdParam)
	// Get product by ID
	// (GET /products/{productId})
	GetProduct(c *gin.Context, productId ProductIdParam)
	// Update product
	// (PUT /products/{productId})
	UpdateProduct(c *gin.Context, productId ProductIdParam)
	// List suppliers
	// (GET /suppliers)
	ListSuppliers(c *gin.Context, params ListSuppliersParams)
	// Create supplier
	// (POST /suppliers)
	CreateSupplier(c *gin.Context)
	// Delete supplier
	// (DELETE /suppliers/{supplierId})
	DeleteSupplier(c *gin.Context, supplierId SupplierIdParam)
	// Get supplier by ID
	// (GET /suppliers/{supplierId})
	GetSupplier(c *gin.Context, supplierId SupplierIdParam)
	// Update supplier
	// (PUT /suppliers/{supplierId})
	UpdateSupplier(c *gin.Context, supplierId SupplierIdParam)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// IssueToken operation middleware
func (siw *ServerInterfaceWrapper) IssueToken(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.IssueToken(c)
}

// ListCategories operation middleware
func (siw *ServerInterfaceWrapper) ListCategories(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{"viewer"})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCategoriesParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", c.Request.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListCategories(c, params)
}

// CreateCategory operation middleware
func (siw *ServerInterfaceWrapper) CreateCategory(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{"admin"})

	c.Set(BearerAuthScopes, []string{"manager"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateCategory(c)
}

// DeleteCategory operation middleware
func (siw *ServerInterfaceWrapper) DeleteCategory(c *gin.Context) {

	var err error

	// ------------- Path parameter "categoryId" -------------
	var categoryId CategoryIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "categoryId", c.Param("categoryId"), &categoryId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter categoryId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{"admin"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteCategory(c, categoryId)
}

// GetCategory operation middleware
func (siw *ServerInterfaceWrapper) GetCategory(c *gin.Context) {

	var err error

	// ------------- Path parameter "categoryId" -------------
	var categoryId CategoryIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "categoryId", c.Param("categoryId"), &categoryId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter categoryId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{"viewer"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCategory(c, categoryId)
}

// UpdateCategory operation middleware
func (siw *ServerInterfaceWrapper) UpdateCategory(c *gin.Context) {

	var err error

	// ------------- Path parameter "categoryId" -------------
	var categoryId CategoryIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "categoryId", c.Param("categoryId"), &categoryId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter categoryId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{"admin"})

	c.Set(BearerAuthScopes, []string{"manager"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateCategory(c, categoryId)
}

// ListProducts operation middleware
func (siw *ServerInterfaceWrapper) ListProducts(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{"viewer"})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProductsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", c.Request.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "categoryId" -------------

	err = runtime.BindQueryParameter("form", true, false, "categoryId", c.Request.URL.Query(), &params.CategoryId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter categoryId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "supplierId" -------------

	err = runtime.BindQueryParameter("form", true, false, "supplierId", c.Request.URL.Query(), &params.SupplierId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter supplierId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "discontinued" -------------

	err = runtime.BindQueryParameter("form", true, false, "discontinued", c.Request.URL.Query(), &params.Discontinued)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter discontinued: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListProducts(c, params)
}

// CreateProduct operation middleware
func (siw *ServerInterfaceWrapper) CreateProduct(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{"admin"})

	c.Set(BearerAuthScopes, []string{"manager"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateProduct(c)
}

// DeleteProduct operation middleware
func (siw *ServerInterfaceWrapper) DeleteProduct(c *gin.Context) {

	var err error

	// ------------- Path parameter "productId" -------------
	var productId ProductIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "productId", c.Param("productId"), &productId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter productId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{"admin"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteProduct(c, productId)
}

// GetProduct operation middleware
func (siw *ServerInterfaceWrapper) GetProduct(c *gin.Context) {

	var err error

	// ------------- Path parameter "productId" -------------
	var productId ProductIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "productId", c.Param("productId"), &productId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter productId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{"viewer"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProduct(c, productId)
}

// UpdateProduct operation middleware
func (siw *ServerInterfaceWrapper) UpdateProduct(c *gin.Context) {

	var err error

	// ------------- Path parameter "productId" -------------
	var productId ProductIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "productId", c.Param("productId"), &productId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter productId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{"admin"})

	c.Set(BearerAuthScopes, []string{"manager"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateProduct(c, productId)
}

// ListSuppliers operation middleware
func (siw *ServerInterfaceWrapper) ListSuppliers(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{"viewer"})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSuppliersParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "companyName" -------------

	err = runtime.BindQueryParameter("form", true, false, "companyName", c.Request.URL.Query(), &params.CompanyName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter companyName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "country" -------------

	err = runtime.BindQueryParameter("form", true, false, "country", c.Request.URL.Query(), &params.Country)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter country: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListSuppliers(c, params)
}

// CreateSupplier operation middleware
func (siw *ServerInterfaceWrapper) CreateSupplier(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{"admin"})

	c.Set(BearerAuthScopes, []string{"manager"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateSupplier(c)
}

// DeleteSupplier operation middleware
func (siw *ServerInterfaceWrapper) DeleteSupplier(c *gin.Context) {

	var err error

	// ------------- Path parameter "supplierId" -------------
	var supplierId SupplierIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "supplierId", c.Param("supplierId"), &supplierId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter supplierId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{"admin"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteSupplier(c, supplierId)
}

// GetSupplier operation middleware
func (siw *ServerInterfaceWrapper) GetSupplier(c *gin.Context) {

	var err error

	// ------------- Path parameter "supplierId" -------------
	var supplierId SupplierIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "supplierId", c.Param("supplierId"), &supplierId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter supplierId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{"viewer"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSupplier(c, supplierId)
}

// UpdateSupplier operation middleware
func (siw *ServerInterfaceWrapper) UpdateSupplier(c *gin.Context) {

	var err error

	// ------------- Path parameter "supplierId" -------------
	var supplierId SupplierIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "supplierId", c.Param("supplierId"), &supplierId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter supplierId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{"admin"})

	c.Set(BearerAuthScopes, []string{"manager"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateSupplier(c, supplierId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/auth/token", wrapper.IssueToken)
	router.GET(options.BaseURL+"/categories", wrapper.ListCategories)
	router.POST(options.BaseURL+"/categories", wrapper.CreateCategory)
	router.DELETE(options.BaseURL+"/categories/:categoryId", wrapper.DeleteCategory)
	router.GET(options.BaseURL+"/categories/:categoryId", wrapper.GetCategory)
	router.PUT(options.BaseURL+"/categories/:categoryId", wrapper.UpdateCategory)
	router.GET(options.BaseURL+"/products", wrapper.ListProducts)
	router.POST(options.BaseURL+"/products", wrapper.CreateProduct)
	router.DELETE(options.BaseURL+"/products/:productId", wrapper.DeleteProduct)
	router.GET(options.BaseURL+"/products/:productId", wrapper.GetProduct)
	router.PUT(options.BaseURL+"/products/:productId", wrapper.UpdateProduct)
	router.GET(options.BaseURL+"/suppliers", wrapper.ListSuppliers)
	router.POST(options.BaseURL+"/suppliers", wrapper.CreateSupplier)
	router.DELETE(options.BaseURL+"/suppliers/:supplierId", wrapper.DeleteSupplier)
	router.GET(options.BaseURL+"/suppliers/:supplierId", wrapper.GetSupplier)
	router.PUT(options.BaseURL+"/suppliers/:supplierId", wrapper.UpdateSupplier)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{
	"H4sIAAAAAAACA+1cW1PcNhT+Kx63M33ZsIakMxneUpp06KQNE0j7kOFB2FpQa0uOLAMbZv97z5Es",
	"X+XLkmVpYN9Y75HORd+5WsudH4okFZxylfmHd35KJEmoolJ/OiKKXgq5PI5O8Dk+Ytw/BCp15c98",
	"DqTwKSyp4JmkX3ImaeQfKpnTmZ+FVzQhuDJhnCU5bLI/89UyxZWMw0oq/dVq5p+QS1pyiWgWSpYq",
	"JpAdfuXxPLmg0lPCk1Tlku8BMy3Ml5zKZSVNCsR+nW9EFySPleY7QYZT9rVPjj/ILa62oogFiBIK",
	"GWVeCh+R8ZBQuLFbsIMAJDN7g2RBMC6nFFEequFjSS3Rt5zKqZCqxxr4lUdvU0mzDJ7MPPhrwW69",
	"BaNx5N0wdeX99OInbyGkhwspjxi/9MBcVPaZKYMtGyYqJMqUhLVGoDxNY0blsO5ZSXV/5VeWsuEK",
	"2kmkgANXjOpvQknhu+iNwg+gbULgLz+CZy8US/DIW1rMmoa883kex+QiplbADj2LxqS1mt8hkN5T",
	"fgnWOHwdOPbK02g9cVd1C35GWQpms5rq9X3Pyy3ExT80VMjVmu9Ir/gI+9FMdW25rmGmKd3SQC8a",
	"EvI9y9RHmkFYzKhDRqI0eJiiiX7wI+Ae9vlhXoXSeYGceQmbVcmPSEn0Z4izZGw9RCTGCdrjD6Ru",
	"q6JlKXYa0uiTPpya2UkcfwCmn6dJ3zy11Tns/FZKIfuNFIqIOhwYRc0yjNCu75QkIT2OuqHmSEhJ",
	"Y20GCCCepvNYBLIyiDY6nIxApWU3LV4ljMt0Lct3NEwLLYa9sgz8o5RKKBIfW0yVtEEvLSarUdqW",
	"3kVyrKWj2lYNGZwmMRnFcdpVBTCq533CJctCAWfNcxrVgHMhREwJ/4YAuX/gipBfcgLM1PKEyk+c",
	"qdaaV8FsPC5JqvPce3pN4/HjrGWrUS1ykOhEspA2zSdyFGfmYmSqFbs2O+anSoT/jkulqT/wD6jI",
	"BOpNpJVGJdnI4UXCqbRvadMCyTqpqUD1SGZaB+JtvJaF3oLEWQWXGn4fE5uldMHsf4rT6RK2MTt1",
	"ZTs9TMfhAKI2WEbYyPs4VUTB/Z5FhNO/dA1ha/mucUgUYVsxqQYMwR1afvDzFD9AUQlf/ulwvSBw",
	"0nNFQtVHP4GfXn/GVHzfDXKu5P10XT/pTkmp6RWcdUuel1PkSUUGlcZRUSTWVh9Mi2CXRYOwrh02",
	"k6VqwFkn0Vi4j2SaHfY3i/3vDKSdTqU6qSFQbTDZlGH5cbKNZX/PdOP2Mp1vzsS/lPf6XUqy7AZK",
	"o0ZoKB86ThiKvJQ65mIpdKcvIhqzBMwdeZos86ThS6M91155RqUtAocBUVLOKuFcZiyU7UMECUMI",
	"MprI2YvT2xQ4QhXWVVAv8mK2oBgzPca9jIKDR1lNs1qSgLOCja5KVqOeo5DybGlsS29JkiKx/wsl",
	"EnYcc5i6YvW96iq57PUXiVmkUdsZbUwDXnPZata2OMXvs4YXNgn04HTNoUlLebPF8GCj6dKrDsW5",
	"nnzSMJeQXE5ROSPehbb/mxzjGAgbi5uO2xiomySW6LHsOzhsT3+A+CTBvNfUMyeEYEkIJ4gSHK3j",
	"Xx4U3iQWlx7GCCS4ZvRGf/+RkuiF4PGyJLG7WMB8ktDN+HMC8s31g4Zu+PjADHUZX4guqD++PT3z",
	"3pwc63m1lgun1X8Kqa5uGI+8oiWAo8JBt65o4S8C39j+wMDfZDi/WngkkoTKkOLmqBEQGo7B3v5e",
	"gOKDzThJGTx6qR/N9DBbm7GuDtpamMCFqNFQxU7MP86ynFrAF2HmFxEtzRwOHJGb8IlihnrZ/J/M",
	"pKZqFD6E7EbcXDUxhz6sHxjca6kPgmDTvK1XrdrT8yIaMbRBhNZ8tUHmLZfuMj/m1xg2PCgC9TQS",
	"+nsNuyxPEoLlijkc7/e/zzxlQxK5zNBXtSdpZ5tX4EKJLqnjkDG/H1Vks8abup7IVJHMq7drGJgm",
	"EFevwSYsqN4SIXHTRO9YDDQ1//Eulh4mMHCcCxPG+l4HFWmu9r5meMx//oA4dL4bcCDC0nmhiGOI",
	"p/hUo3J/e6j8xDFsgLG/okvUorlGSj2Of7YR9hyNV6EWtawdWQ21NQyeFzVyF6ym9irffTxMVOp5",
	"OTElPO1vXIhhKJgW8dGiU0qWsSDRI+MQmb/cHvN3Ql6wKKLG/Q4ONsa5r1B0yFCRerr6G3NGUzWd",
	"YxBtfmELpZabGuhbR132uWkzxczvqvHmyhRCMYTxrhf/qp83vLjhRa8cL+os5M2ezxpyxj7b4Vza",
	"nQsFFWzOo6lQa+DJnPgonmbuEuU3qvrBEmw35EZUEYbF2KPj73+NAnf2h4MsMYDV2vGvAwXAWmVo",
	"+0IZ8k1zB5bM8GdLFURz0rTlBmcSnIvB8q6CeL7h/MkWMcb7JhUxdvAy2CWfWKLvrke26m2mQ3Zd",
	"IJjEugz9zRtWLv7NF+UTL5VOEMHO1CaI0Hg9v0ER6pc4vEVMes+gdfGkc3m1vObxoPMJ150DhzMX",
	"ZE9gOpFWbm7jRen5Y5MJe53iYcoK94WH7c4lygsjAxDYTSWeZU0hZBVen0N9UQxJ0tLnHeGiXlzM",
	"78pfTkwYj9RDydh0xHrebjiyVeRbs29kNjIIo/7BSC9Mgm2G/Gc5FVn7+PuHIsXhd2YizcJjvaaj",
	"+VOukYHIVgqXRx2HTEDxbhjy3MP3U5+FjNYq5Z2TwUnIaUn13Y1CSgX1QMLcgZw4E2lez3WPRoI1",
	"RiMtUfQ91H7e5ppqD9+ft3xpwXk51AFrS/cExgJZDfPWeSo/GBsMlFdfHybB9txN3e5ooLreOwSE",
	"3XBgd2XhAbvxrHI0l5c2ctz8rprxTujIGz481pKXgN/15Fst6k4dE6j7N+UjaOpvy/uxEmw33j7L",
	"znx9EPS35uVIs92bt5L/WmVw+5+NjHTnW6oeHrU/n4TmXYf+7IP5U2/RxwqYQaZmSyqvbRxyTjzw",
	"w8zP9e9arpRKs8P5nKRsr/hJ1B7YydFAvxchiSGfXNNYpAlavr4HbBEjwRU0QYevg9eBjmmFBr23",
	"OY0pcDOP8igVDM5mr+p6a/c0uvLY8c3IHuWAo7tDCa+RLSr7d/dAw+NNgrBAhmO5PpvV+eo/wh6B",
	"+RNNAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
