// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Category defines model for Category.
type Category struct {
	CreatedAt   time.Time `json:"createdAt"`
	Description *string   `json:"description"`
	Id          int       `json:"id"`
	Name        string    `json:"name"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

// CategoryCreateRequest defines model for CategoryCreateRequest.
type CategoryCreateRequest struct {
	Description *string `json:"description"`
	Name        string  `json:"name"`
}

// CategoryListResponse defines model for CategoryListResponse.
type CategoryListResponse struct {
	Data []Category     `json:"data"`
	Meta PaginationMeta `json:"meta"`
}

// CategoryUpdateRequest defines model for CategoryUpdateRequest.
type CategoryUpdateRequest = CategoryCreateRequest

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`

	// TraceId Correlation or trace identifier.
	TraceId *string `json:"traceId"`
}

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	Page       int `json:"page"`
	PageSize   int `json:"pageSize"`
	TotalItems int `json:"totalItems"`
	TotalPages int `json:"totalPages"`
}

// Product defines model for Product.
type Product struct {
	CategoryId      int       `json:"categoryId"`
	CreatedAt       time.Time `json:"createdAt"`
	Discontinued    bool      `json:"discontinued"`
	Id              int       `json:"id"`
	Name            string    `json:"name"`
	QuantityPerUnit *string   `json:"quantityPerUnit"`
	ReorderLevel    *int      `json:"reorderLevel,omitempty"`
	SupplierId      int       `json:"supplierId"`
	UnitPrice       float64   `json:"unitPrice"`
	UnitsInStock    int       `json:"unitsInStock"`
	UnitsOnOrder    *int      `json:"unitsOnOrder,omitempty"`
	UpdatedAt       time.Time `json:"updatedAt"`
}

// ProductCreateRequest defines model for ProductCreateRequest.
type ProductCreateRequest struct {
	CategoryId      int     `json:"categoryId"`
	Discontinued    *bool   `json:"discontinued,omitempty"`
	Name            string  `json:"name"`
	QuantityPerUnit *string `json:"quantityPerUnit"`
	ReorderLevel    *int    `json:"reorderLevel,omitempty"`
	SupplierId      int     `json:"supplierId"`
	UnitPrice       float64 `json:"unitPrice"`
	UnitsInStock    *int    `json:"unitsInStock,omitempty"`
	UnitsOnOrder    *int    `json:"unitsOnOrder,omitempty"`
}

// ProductListResponse defines model for ProductListResponse.
type ProductListResponse struct {
	Data []Product      `json:"data"`
	Meta PaginationMeta `json:"meta"`
}

// ProductUpdateRequest defines model for ProductUpdateRequest.
type ProductUpdateRequest = ProductCreateRequest

// Supplier defines model for Supplier.
type Supplier struct {
	Address      *string   `json:"address"`
	City         *string   `json:"city"`
	CompanyName  string    `json:"companyName"`
	ContactName  *string   `json:"contactName"`
	ContactTitle *string   `json:"contactTitle"`
	Country      *string   `json:"country"`
	CreatedAt    time.Time `json:"createdAt"`
	Id           int       `json:"id"`
	Phone        *string   `json:"phone"`
	PostalCode   *string   `json:"postalCode"`
	Region       *string   `json:"region"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

// SupplierCreateRequest defines model for SupplierCreateRequest.
type SupplierCreateRequest struct {
	Address      *string `json:"address"`
	City         *string `json:"city"`
	CompanyName  string  `json:"companyName"`
	ContactName  *string `json:"contactName"`
	ContactTitle *string `json:"contactTitle"`
	Country      *string `json:"country"`
	Phone        *string `json:"phone"`
	PostalCode   *string `json:"postalCode"`
	Region       *string `json:"region"`
}

// SupplierListResponse defines model for SupplierListResponse.
type SupplierListResponse struct {
	Data []Supplier     `json:"data"`
	Meta PaginationMeta `json:"meta"`
}

// SupplierUpdateRequest defines model for SupplierUpdateRequest.
type SupplierUpdateRequest = SupplierCreateRequest

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	Password string `json:"password"`

	// Scope Space-delimited scopes requested.
	Scope    string `json:"scope"`
	Username string `json:"username"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken string `json:"accessToken"`

	// ExpiresIn Token lifetime in seconds.
	ExpiresIn    int     `json:"expiresIn"`
	RefreshToken *string `json:"refreshToken"`
	TokenType    string  `json:"tokenType"`
}

// ValidationErrorResponse defines model for ValidationErrorResponse.
type ValidationErrorResponse struct {
	Code   string `json:"code"`
	Errors *[]struct {
		Field   string `json:"field"`
		Message string `json:"message"`
	} `json:"errors,omitempty"`
	Message string `json:"message"`

	// TraceId Correlation or trace identifier.
	TraceId *string `json:"traceId"`
}

// CategoryIdParam defines model for CategoryIdParam.
type CategoryIdParam = int

// PageParam defines model for PageParam.
type PageParam = int

// PageSizeParam defines model for PageSizeParam.
type PageSizeParam = int

// ProductIdParam defines model for ProductIdParam.
type ProductIdParam = int

// SortParam defines model for SortParam.
type SortParam = string

// SupplierIdParam defines model for SupplierIdParam.
type SupplierIdParam = int

// ListCategoriesParams defines parameters for ListCategories.
type ListCategoriesParams struct {
	// Page Page number to return.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Maximum number of records per page.
	PageSize *PageSizeParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`

	// Sort Sort expression, prefix field with '-' for descending order.
	Sort *SortParam `form:"sort,omitempty" json:"sort,omitempty"`

	// Name Filter categories by name substring.
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// ListProductsParams defines parameters for ListProducts.
type ListProductsParams struct {
	// Page Page number to return.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Maximum number of records per page.
	PageSize *PageSizeParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`

	// Sort Sort expression, prefix field with '-' for descending order.
	Sort *SortParam `form:"sort,omitempty" json:"sort,omitempty"`

	// Name Filter products by name substring.
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// CategoryId Filter products by category identifier.
	CategoryId *int `form:"categoryId,omitempty" json:"categoryId,omitempty"`

	// SupplierId Filter products by supplier identifier.
	SupplierId *int `form:"supplierId,omitempty" json:"supplierId,omitempty"`

	// Discontinued Filter products by discontinued flag.
	Discontinued *bool `form:"discontinued,omitempty" json:"discontinued,omitempty"`
}

// ListSuppliersParams defines parameters for ListSuppliers.
type ListSuppliersParams struct {
	// Page Page number to return.
	Page *PageParam `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Maximum number of records per page.
	PageSize *PageSizeParam `form:"pageSize,omitempty" json:"pageSize,omitempty"`

	// Sort Sort expression, prefix field with '-' for descending order.
	Sort *SortParam `form:"sort,omitempty" json:"sort,omitempty"`

	// CompanyName Filter suppliers by company name substring.
	CompanyName *string `form:"companyName,omitempty" json:"companyName,omitempty"`

	// Country Filter suppliers by country.
	Country *string `form:"country,omitempty" json:"country,omitempty"`
}

// IssueTokenJSONRequestBody defines body for IssueToken for application/json ContentType.
type IssueTokenJSONRequestBody = TokenRequest

// CreateCategoryJSONRequestBody defines body for CreateCategory for application/json ContentType.
type CreateCategoryJSONRequestBody = CategoryCreateRequest

// UpdateCategoryJSONRequestBody defines body for UpdateCategory for application/json ContentType.
type UpdateCategoryJSONRequestBody = CategoryUpdateRequest

// CreateProductJSONRequestBody defines body for CreateProduct for application/json ContentType.
type CreateProductJSONRequestBody = ProductCreateRequest

// UpdateProductJSONRequestBody defines body for UpdateProduct for application/json ContentType.
type UpdateProductJSONRequestBody = ProductUpdateRequest

// CreateSupplierJSONRequestBody defines body for CreateSupplier for application/json ContentType.
type CreateSupplierJSONRequestBody = SupplierCreateRequest

// UpdateSupplierJSONRequestBody defines body for UpdateSupplier for application/json ContentType.
type UpdateSupplierJSONRequestBody = SupplierUpdateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Issue JWT token
	// (POST /auth/token)
	IssueToken(c *gin.Context)
	// List categories
	// (GET /categories)
	ListCategories(c *gin.Context, params ListCategoriesParams)
	// Create category
	// (POST /categories)
	CreateCategory(c *gin.Context)
	// Delete category
	// (DELETE /categories/{categoryId})
	DeleteCategory(c *gin.Context, categoryId CategoryIdParam)
	// Get category by ID
	// (GET /categories/{categoryId})
	GetCategory(c *gin.Context, categoryId CategoryIdParam)
	// Update category
	// (PUT /categories/{categoryId})
	UpdateCategory(c *gin.Context, categoryId CategoryIdParam)
	// List products
	// (GET /products)
	ListProducts(c *gin.Context, params ListProductsParams)
	// Create product
	// (POST /products)
	CreateProduct(c *gin.Context)
	// Delete product
	// (DELETE /products/{productId})
	DeleteProduct(c *gin.Context, productId ProductIdParam)
	// Get product by ID
	// (GET /products/{productId})
	GetProduct(c *gin.Context, productId ProductIdParam)
	// Update product
	// (PUT /products/{productId})
	UpdateProduct(c *gin.Context, productId ProductIdParam)
	// List suppliers
	// (GET /suppliers)
	ListSuppliers(c *gin.Context, params ListSuppliersParams)
	// Create supplier
	// (POST /suppliers)
	CreateSupplier(c *gin.Context)
	// Delete supplier
	// (DELETE /suppliers/{supplierId})
	DeleteSupplier(c *gin.Context, supplierId SupplierIdParam)
	// Get supplier by ID
	// (GET /suppliers/{supplierId})
	GetSupplier(c *gin.Context, supplierId SupplierIdParam)
	// Update supplier
	// (PUT /suppliers/{supplierId})
	UpdateSupplier(c *gin.Context, supplierId SupplierIdParam)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// IssueToken operation middleware
func (siw *ServerInterfaceWrapper) IssueToken(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.IssueToken(c)
}

// ListCategories operation middleware
func (siw *ServerInterfaceWrapper) ListCategories(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{"viewer"})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCategoriesParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", c.Request.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListCategories(c, params)
}

// CreateCategory operation middleware
func (siw *ServerInterfaceWrapper) CreateCategory(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{"admin"})

	c.Set(BearerAuthScopes, []string{"manager"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateCategory(c)
}

// DeleteCategory operation middleware
func (siw *ServerInterfaceWrapper) DeleteCategory(c *gin.Context) {

	var err error

	// ------------- Path parameter "categoryId" -------------
	var categoryId CategoryIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "categoryId", c.Param("categoryId"), &categoryId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter categoryId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{"admin"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteCategory(c, categoryId)
}

// GetCategory operation middleware
func (siw *ServerInterfaceWrapper) GetCategory(c *gin.Context) {

	var err error

	// ------------- Path parameter "categoryId" -------------
	var categoryId CategoryIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "categoryId", c.Param("categoryId"), &categoryId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter categoryId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{"viewer"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCategory(c, categoryId)
}

// UpdateCategory operation middleware
func (siw *ServerInterfaceWrapper) UpdateCategory(c *gin.Context) {

	var err error

	// ------------- Path parameter "categoryId" -------------
	var categoryId CategoryIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "categoryId", c.Param("categoryId"), &categoryId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter categoryId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{"admin"})

	c.Set(BearerAuthScopes, []string{"manager"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateCategory(c, categoryId)
}

// ListProducts operation middleware
func (siw *ServerInterfaceWrapper) ListProducts(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{"viewer"})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProductsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", c.Request.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "categoryId" -------------

	err = runtime.BindQueryParameter("form", true, false, "categoryId", c.Request.URL.Query(), &params.CategoryId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter categoryId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "supplierId" -------------

	err = runtime.BindQueryParameter("form", true, false, "supplierId", c.Request.URL.Query(), &params.SupplierId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter supplierId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "discontinued" -------------

	err = runtime.BindQueryParameter("form", true, false, "discontinued", c.Request.URL.Query(), &params.Discontinued)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter discontinued: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListProducts(c, params)
}

// CreateProduct operation middleware
func (siw *ServerInterfaceWrapper) CreateProduct(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{"admin"})

	c.Set(BearerAuthScopes, []string{"manager"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateProduct(c)
}

// DeleteProduct operation middleware
func (siw *ServerInterfaceWrapper) DeleteProduct(c *gin.Context) {

	var err error

	// ------------- Path parameter "productId" -------------
	var productId ProductIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "productId", c.Param("productId"), &productId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter productId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{"admin"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteProduct(c, productId)
}

// GetProduct operation middleware
func (siw *ServerInterfaceWrapper) GetProduct(c *gin.Context) {

	var err error

	// ------------- Path parameter "productId" -------------
	var productId ProductIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "productId", c.Param("productId"), &productId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter productId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{"viewer"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProduct(c, productId)
}

// UpdateProduct operation middleware
func (siw *ServerInterfaceWrapper) UpdateProduct(c *gin.Context) {

	var err error

	// ------------- Path parameter "productId" -------------
	var productId ProductIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "productId", c.Param("productId"), &productId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter productId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{"admin"})

	c.Set(BearerAuthScopes, []string{"manager"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateProduct(c, productId)
}

// ListSuppliers operation middleware
func (siw *ServerInterfaceWrapper) ListSuppliers(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{"viewer"})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSuppliersParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "companyName" -------------

	err = runtime.BindQueryParameter("form", true, false, "companyName", c.Request.URL.Query(), &params.CompanyName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter companyName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "country" -------------

	err = runtime.BindQueryParameter("form", true, false, "country", c.Request.URL.Query(), &params.Country)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter country: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListSuppliers(c, params)
}

// CreateSupplier operation middleware
func (siw *ServerInterfaceWrapper) CreateSupplier(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{"admin"})

	c.Set(BearerAuthScopes, []string{"manager"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateSupplier(c)
}

// DeleteSupplier operation middleware
func (siw *ServerInterfaceWrapper) DeleteSupplier(c *gin.Context) {

	var err error

	// ------------- Path parameter "supplierId" -------------
	var supplierId SupplierIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "supplierId", c.Param("supplierId"), &supplierId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter supplierId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{"admin"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteSupplier(c, supplierId)
}

// GetSupplier operation middleware
func (siw *ServerInterfaceWrapper) GetSupplier(c *gin.Context) {

	var err error

	// ------------- Path parameter "supplierId" -------------
	var supplierId SupplierIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "supplierId", c.Param("supplierId"), &supplierId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter supplierId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{"viewer"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSupplier(c, supplierId)
}

// UpdateSupplier operation middleware
func (siw *ServerInterfaceWrapper) UpdateSupplier(c *gin.Context) {

	var err error

	// ------------- Path parameter "supplierId" -------------
	var supplierId SupplierIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "supplierId", c.Param("supplierId"), &supplierId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter supplierId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{"admin"})

	c.Set(BearerAuthScopes, []string{"manager"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateSupplier(c, supplierId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/auth/token", wrapper.IssueToken)
	router.GET(options.BaseURL+"/categories", wrapper.ListCategories)
	router.POST(options.BaseURL+"/categories", wrapper.CreateCategory)
	router.DELETE(options.BaseURL+"/categories/:categoryId", wrapper.DeleteCategory)
	router.GET(options.BaseURL+"/categories/:categoryId", wrapper.GetCategory)
	router.PUT(options.BaseURL+"/categories/:categoryId", wrapper.UpdateCategory)
	router.GET(options.BaseURL+"/products", wrapper.ListProducts)
	router.POST(options.BaseURL+"/products", wrapper.CreateProduct)
	router.DELETE(options.BaseURL+"/products/:productId", wrapper.DeleteProduct)
	router.GET(options.BaseURL+"/products/:productId", wrapper.GetProduct)
	router.PUT(options.BaseURL+"/products/:productId", wrapper.UpdateProduct)
	router.GET(options.BaseURL+"/suppliers", wrapper.ListSuppliers)
	router.POST(options.BaseURL+"/suppliers", wrapper.CreateSupplier)
	router.DELETE(options.BaseURL+"/suppliers/:supplierId", wrapper.DeleteSupplier)
	router.GET(options.BaseURL+"/suppliers/:supplierId", wrapper.GetSupplier)
	router.PUT(options.BaseURL+"/suppliers/:supplierId", wrapper.UpdateSupplier)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xcW2/bOBb+KwR3gXlRYyXtAIXfOpnpIIt2GjTp7kORB0Y8tjkjkSpJJfEE/u8LkrqL",
	"ujjjOG3it0Y6JM85/M6Fn+je40gkqeDAtcLze5wSSRLQIO1fp0TDUsj1GT03z80jxvEcp0SvcIA5SQDP",
	"cVRK4QBL+JYxCRTPtcwgwCpaQULMyIRxlmQJnh8HWK9TM5JxDUuQeLMJ8DlZQrkKBRVJlmomzHLmFeJZ",
	"cg0SaYEk6EzyIxw4Zb5lINeVNilZAq6vS2FBsljbdSfocMH+7tPjI7kzowtVxAJJiISkCqUgkVl4SCkz",
	"sV+xkzDAiZsbz4/DcFxPKWgW6eFtSQuhf7IrF0LqHm+YVwjuUglKMcEDlEpYsDu0YBBTdMv0Cv306ie0",
	"EBKZgcAp40skJAXZ5yYlpG64KNdIacn40imUpWnMQA7brkqphxu/KSQboWCDRIoUpGZg30QSiAb6Tps/",
	"FkImROM5pkTDK80Ss+UtK4KmI+8xz+KYXMdQKNiRZ3RM28LyewOkD8CXeoXnb0PPXFlKt1N3U/fgV6NL",
	"vlhQM70+71U5hbj+EyJtVi3cd2pHfIZvGSjd9eW2jplmdMsCO2hIyQ9M6c+gUsEVeHQk2oKHaUjsg39L",
	"WOA5/tesSqWzHDmzEjabcj0iJbF/J+AmGhp/TpaME+OPj0a6bYrVJZ9pyKIvdnNqbidx/GmB51+nad/c",
	"tc3VJsC/SSlkv5MiQcETwEZVpUyG9r3TkkRwRrup5lRICbF1AxISWTnEKHDNFsylkxGotPxm1auU8bmu",
	"5fmOhWluxXBUlol/VFILTeKzAlOlbNgra4rVqGzL7rw41spRbaqGDl6XuIri2e2qAxi18yHpkqlIcM14",
	"BrQGnGshYiD8HyTI4xNfhvyWEa6ZXp+D/MKZbo15EwbjeUmCrXMf4Abi8e2sVatRKzLO9LlkETTdJzKj",
	"TuBbyHUrxVh1xi+0iP4a18pKf+KfjCETpHdRVhqdZKOG5wWnsr5lTQsk25SmHNUjlWkbiLfxWjZ6CxKr",
	"Ci41/D4lNkvtwuA7xel0DduYnTqyXR6m43AAUTtsI4rM+zRdRL76A5sIb3zZHqLo5bvOIZSaY8WkHjBi",
	"et2Kg5+nxIFRlfD1H57QC0OvPNck0n3yE9az4y+Zjh86Qca1fJit2xfdKSU1XQnetuX1FH1SoTSJT/Mm",
	"sTb6ZFoGW+YHhG39sJsqVQPONoWmgPtIpTlgf7fY/8FA2jmpVDs1BKodFpsyLT9NtSmWf2C58UeZrTeX",
	"4i/gvXGXEqVuhaSN1FA+9OywikQKHl4sJRG8ohCzhGmgyIopJN26QI98c2UKZNEEDgOilAzqyjldfO7M",
	"je5DBokiUMoKec/kcJcyCeqMdw21g1DMFmByJ2IcKYgEp6pmYa1YSFhIUKtyqdEI0kbycu18DHckSY0w",
	"/gWIBDmaquuG1eeqm+Tz139JzKhFb4fimAbA5rBN0PY4mPeqEY1NAUugbkmetIx3UwwTHM3Q3nQkriwD",
	"ClEmmV5fGOOcetfW/+8yk8/u8SIWt53wcZB3xSyx9Oz7LI6R/YMpLYlmN4DcDhmwJIQTg5I5/mj/hSKi",
	"SSyWyOQKI3DD4Na+/wyEvhI8XpcixSwFYL7IGM/xjGR6NbMPGraZxyeO3GV8Ibqg/vzbxSV6d35meWur",
	"F+NL9IeQenXLOEX50YCBClDOsKsAEU5RcU5w8HeVDlcDT0WSgIzATG4sAqnciuHR8VFo1BcpcJIyPMev",
	"7aPAktrWjXVzjK+FS2AGNRaq5kSGz5TKoAB8nm5+EXTt+Diugbs0atSM7LDZn8qVqIoSH0J2I39umpgz",
	"MWwfONxbrU/CcNdrF1G1abPoeTZixgfUePPNDhdvhXR38TN+Y9IGiiRYVpLEysJOZUlCTNviNgf953+X",
	"SBcpiSyViVUbSTbYZhW4jEZL8GyyqfOnlVjQ+GLXk5kqkVn1lc0kpgnC1eewCQOqr0VGuOmi9yzWIGvx",
	"g67XyBQypLJrl8b6Pgvl5a723WaY7r96RBx6vxF4EFHIoUjEMUT2qUXl8f5Q+YWbtCEk+9uERC2bW6TU",
	"8/jXIsNeGedVqDVW1rashtoaBq/yXrkLVteDld9AHicr9XykmJKejneuxDAU3FHxybJTStaxIPSJcWgW",
	"f72/xd8Lec0oBRd+Jyc7W7mvUfToUIki2/2NBaPrmq5MEm2+KBqlVpg66BeBuu4L02aJmd1XNOfGNUIx",
	"aOhG8a/2eSOKG1H0xvPBroC8m/NFQ875Zz8rl37nQqOFyDidCrUGntyOj+Ip8Lcov4PuB0u435RLQRNm",
	"mrEnx993jQJ/9f8dyuK/Nt3a2a8DDcBWbWj7YplZN808WHIk0J46iCbjtOcDziQ45wTzoYN4uen82TYx",
	"LvomNTEF8TJ4Sj4vhH64M3Jh3m5OyL6LBJOWLlN/86aVb/3mB/OJl0snqFBwahNUaHym36EK9cscaBGT",
	"3j1oXUDpXGItr3s8Kj/hu3vgCeZc7BmwE2kV5kW+KCN/jJkorlU8Tlvhv/iwX16ivDgyAIEDK/Eiewoh",
	"q/T6EvqLnCRJy5j3pIt6czG7L39BMYEeqaeSMXakiLwDObJX5Bdu3wk3MgijfmKkFybhPlP+i2RFtt7+",
	"flIk3/wOJ9JsPLY7dDR/0jVCiOylcXlSOmQCig9kyEtP38+dCxntVco7J4NMyEUp9cNRIaWBlpBwdyEn",
	"ciLNa7p+aiTcghppqWLvo/av7a6r9qz7854vLXgviXpgXcg9A1pA1TBfBE8VB2PEQHkF9nEKbM8d1f1S",
	"A9U13yEgHMiBw5WFRzyNqyrQfFHaqHGz+4rjnXAib8Tw2JG8BPzhTL7Xpu7Cw0A9/FA+gqb+Y3k/VsL9",
	"5tsXeTLfHgT9R/OS0myfzVvFf6s2uP2fjoyczvfUPTzp+XwSmg8n9BefzJ/7EX2sgRlc1E0J8qbIQ17G",
	"w/wR4Mz+rmWldarmsxlJ2VH+k6ijSPgO0B9ERGJE4QZikSbG8/U55rNZbARWQun52/BtaHNabkHvbU7n",
	"CjMZAk5Twbi2v3bJT721expdfQr6ZmSOkuDozlDCa2SKyv/dOYzjgescfd7hdm82V5v/BwAA//9Vhymu",
	"G00AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
